export { Messenger } from './Icons/Messenger'
export { Facebook } from './Icons/Facebook'
export { Notifications } from './Icons/Notifications'
export { Market } from './Icons/Market'
export { Group } from './Icons/Group'
export { Gaming } from './Icons/Gaming'
export { Search } from 'styled-icons/material-outlined'
export { Menu } from 'styled-icons/heroicons-outline'
export { Plus } from 'styled-icons/heroicons-solid'
export { ArrowDropDown, Home, OndemandVideo as Watch } from 'styled-icons/material-rounded'
